### ISSUE TITLE
Using the library with Java 11 and Spring Boot might cause an UnsupportedOperationException because of Log4J

### ISSUE THREAD

**Issue by ManuelB** [DKE-Data/agrirouter-sdk-java#146]
**Describe the bug**
Using the library with Java 11 and Spring Boot might cause an UnsupportedOperationException because of Log4J. This is due to Log4J does not correctly implement the Java Module System introduced in Java 9.

**To Reproduce**
 1. Use Java 11 and Spring Boot 2.0.3
 2. Build a Spring Boot application without multi-release that includes the api
 3. Try to use the API

**Actual behavior**
```
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
	at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:571)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:596)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:583)
	at com.dke.data.agrirouter.api.service.LoggingEnabledService.<clinit>(LoggingEnabledService.java:30)
	... 59 common frames omitted
```

**Expected behavior**
Should just work.

**Screenshots**
![Screenshot from 2021-02-18 08-29-28](https://user-images.githubusercontent.com/457641/108320737-7f1b7780-71c3-11eb-9d13-d8e93556952d.png)

**Server (please complete the following information):**
 - OS: Linux, OpenJDK 11 & Oracle Java SDK 12, Spring Boot 2.0.3, Log4J 2.10

**Fix:**
- Pin version 2.14 of log4j in pom.xml and use Spring Boot 2.4.2

**Additional context**
https://github.com/spring-projects/spring-boot/issues/12523
https://stackoverflow.com/questions/52953483/logmanager-getlogger-is-unable-to-determine-class-name-on-java-11

**Comment by keilw** [comment]
Just a gut feeling, did you try it with Java 16, see this [JDK-8235229](https://bugs.openjdk.java.net/browse/JDK-8235229) bug only fixed with 16?

**Comment by ManuelB** [comment]
@keilw we updated spring. Nevertheless I wanted to share this issue here and a solution.
