### ISSUE TITLE
Publish SDK to Maven Central

### ISSUE THREAD

**Issue by agriopt-vikgus** [DKE-Data/agrirouter-sdk-java#154]
**Is your feature request related to a problem? Please describe.**
Using github packages is time consuming, especially when one wishes to publish to a container. I had many issues with App Engine deployment. For instance, it was not obvious what the agrirouter url to refer to in settings.xml is. It also took me a long time to figure out that I explicitly har to enable Snapshots and releases in the settings.xml. Also, configuring settings.xml on a container was troublesome.

**Describe the solution you'd like**
Publish to Maven Central. This makes boilerplate such as mvn app-engine:deploy work without any issues.

**Describe alternatives you've considered**
Include documentation on how to add the github packages to user Maven settings. Add a boilerplate settings.xml somewhere. Include that you can use a local settings.xml when running Maven like so: mvn -s "settings.xml" (useful for container deployment).

**Comment by saschadoemer** [comment]
The artifacts will be uploaded manually and there is a new section for usage description with #166.
