### ISSUE TITLE
application/json repeated twice in Accept header

### ISSUE THREAD

**Issue by tim-reply** [DKE-Data/agrirouter-sdk-java#214]
**Describe the bug**
When querying http service, accept header is added twice:
"1 > Accept: application/json,application/json"

**To Reproduce**

1. use FetchMessageService.fetch
2. check in logs , it would have this:
```
1 > Accept: application/json,application/json
```

**Expected behavior**
should only send application/json once

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04

**Additional context**
I think the issue is here:
https://github.com/DKE-Data/agrirouter-sdk-java/blob/ca24abb35e109104679763f2bf987ae3a5727ebc/agrirouter-sdk-java-impl/src/main/java/com/dke/data/agrirouter/impl/RequestFactory.java#L57-L58

**Comment by saschadoemer** [comment]
Hey @tim-reply,

thanks a lot, I will take a look at it and provide a fix.

Regards

Sascha
