### ISSUE TITLE
`com.dke.data.agrirouter.impl.messaging.rest.SetCapabilityServiceImpl` is an `EnvironmentalService`, but probably shouldn't be

### ISSUE THREAD

**Issue by oliverrahner** [DKE-Data/agrirouter-sdk-java#215]
**Describe the bug**
When instantiating the SetCapabilityServiceImpl for REST communication, I need to pass an environment, but it is never used anywhere.
For MQTT, this is not the case.

**Comment by saschadoemer** [comment]
[like]  Sascha Dömer reacted to your message:
________________________________
From: Oliver Rahner ***@***.***>
Sent: Wednesday, May 15, 2024 8:46:17 AM
To: DKE-Data/agrirouter-sdk-java ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DKE-Data/agrirouter-sdk-java] `com.dke.data.agrirouter.impl.messaging.rest.SetCapabilityServiceImpl` is an `EnvironmentalService`, but probably shouldn't be (Issue #215)


Describe the bug
When instantiating the SetCapabilityServiceImpl for REST communication, I need to pass an environment, but it is never used anywhere.
For MQTT, this is not the case.
